version: '3'
services:
  tor:
    image: "dperson/torproxy"
    restart: unless-stopped
    networks:
      - proxy

  todayincinema:
    environment:
      - BOT_TOKEN=
    build: .
    restart: unless-stopped
    networks:
      - proxy
    depends_on:
      - "tor"


networks:
  proxy:
    driver: bridge